### ISSUE TITLE
Time for another release?

### ISSUE THREAD

**Issue by tommy-gilligan** [rahul-thakoor/embedded-graphics-web-simulator#47]
Hi! Love your work <3

I'm using `embedded-graphics` 0.8 but `embedded-graphics-web-simulator` only supports this in repo.  I think it would be nice to put out another release.

**Comment by rahul-thakoor** [comment]
Thanks

Just published [v0.4.0](https://crates.io/crates/embedded-graphics-web-simulator/0.4.0)

thanks to @spookyvision for their contribution 🎉
